baseURL = 'https://guilferri.netlify.com/'
languageCode = 'pt-br'
defaultContentLanguage = 'pt-br'
title = 'Guilherme Ferreira'
disableKinds = ['taxonomy', 'taxonomyTerm']

[menu]
  [[menu.main]]
        identifier = 'blog'
        name = 'ğŸ“ Blog'
        url = '/posts/'
        weight = 2

  [[menu.main]]
        identifier = 'home'
        name = 'ğŸ  InÃ­cio'
        url = '/'
        weight = 1
